"""empty message

Revision ID: 3a0514c32fa5
Revises: None
Create Date: 2016-01-05 20:54:24.646401

"""

# revision identifiers, used by Alembic.
revision = '3a0514c32fa5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
